unit TestuProdutoControl;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, FireDAC.Comp.Client, uProdutoControl, System.SysUtils,
  uProdutoModel, uEnumerado, Vcl.Forms;

type
  // Test methods for class TProdutoControl

  TestTProdutoControl = class(TTestCase)
  strict private
    FProdutoControl: TProdutoControl;
    ATipo: TAcao;
    ReturnValue: Boolean;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestObterProdDesc;
    procedure TestObterCodBarra;
    procedure TestGetId;
    procedure TestIncluir;
    procedure TesteAlterar;
    procedure TesteExcluir;
    procedure TestSalvar;
    procedure TestObter;
  end;

implementation

procedure TestTProdutoControl.SetUp;
begin
  FProdutoControl := TProdutoControl.Create;
end;

procedure TestTProdutoControl.TearDown;
begin
  FProdutoControl.Free;
  FProdutoControl := nil;
end;

procedure TestTProdutoControl.TestSalvar;
var
  ReturnValue: Boolean;
begin
  ReturnValue := FProdutoControl.Salvar;
end;

procedure TestTProdutoControl.TestObter;
var
  ReturnValue: TFDQuery;
  AValorparcial: string;
  AorderBy: Integer;
begin
  AValorparcial := '';
  AorderBy := 1;
  ReturnValue := FProdutoControl.Obter(AorderBy, AValorparcial);
end;

procedure TestTProdutoControl.TestObterProdDesc;
var
  ReturnValue: TFDQuery;
  AValorpesquisa: string;
begin
  AValorpesquisa := '1';
  ReturnValue := FProdutoControl.ObterProdDesc(AValorpesquisa);
end;

procedure TestTProdutoControl.TestObterCodBarra;
var
  ReturnValue: TFDQuery;
  AValorpesquisa: string;
begin
  AValorpesquisa := '1';
  ReturnValue := FProdutoControl.ObterCodBarra(AValorpesquisa);
end;

procedure TestTProdutoControl.TestIncluir;
begin
  ATipo := uEnumerado.tacIncluir;
  FProdutoControl.ProdutoModel.Acao        := ATipo;
  FProdutoControl.ProdutoModel.Codigo      := FProdutoControl.ProdutoModel.GetId;
  FProdutoControl.ProdutoModel.Codigobarra := '9999999999999';
  FProdutoControl.ProdutoModel.Descricao   := 'PRODUTO DE TESTE UNITARIO - ' + IntToStr(FProdutoControl.ProdutoModel.Codigo);
  FProdutoControl.ProdutoModel.PRECOCOMPRA := 1.5;
  FProdutoControl.ProdutoModel.PRECOVENDA  := 1.6;
  FProdutoControl.ProdutoModel.QTDEESTOQUE := 1;
  FProdutoControl.ProdutoModel.CATEGORIAPRD := 8;
  ReturnValue := FProdutoControl.Salvar;
end;

procedure TestTProdutoControl.TesteAlterar;
begin
  ATipo := uEnumerado.tacAlterar;
  FProdutoControl.ProdutoModel.Acao        := ATipo;
  FProdutoControl.ProdutoModel.Codigo      := FProdutoControl.ProdutoModel.GetId -1;
  FProdutoControl.ProdutoModel.Codigobarra := '9999999999999';
  FProdutoControl.ProdutoModel.Descricao   := 'PRODUTO DE TESTE UNITARIO ALTERANDO - ' + IntToStr(FProdutoControl.ProdutoModel.Codigo);
  FProdutoControl.ProdutoModel.PRECOCOMPRA := 1.5;
  FProdutoControl.ProdutoModel.PRECOVENDA  := 1.6;
  FProdutoControl.ProdutoModel.QTDEESTOQUE := 1;
  FProdutoControl.ProdutoModel.CATEGORIAPRD := 8;
  ReturnValue := FProdutoControl.Salvar;
end;

procedure TestTProdutoControl.TesteExcluir;
begin
  ATipo := uEnumerado.tacExcluir;
  FProdutoControl.ProdutoModel.Acao        := ATipo;
  FProdutoControl.ProdutoModel.Codigo      := FProdutoControl.ProdutoModel.GetId -1;
  ReturnValue := FProdutoControl.Salvar;
end;

procedure TestTProdutoControl.TestGetId;
var
  ReturnValue: Integer;
begin
  ReturnValue := FProdutoControl.GetId;
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTProdutoControl.Suite);
end.

