INSERT INTO PRODUTOS (ID, CODIGO_BAR, DESCRICAO, PRECO_COMPRA, PRECO_VENDA, QTD_ESTOQUE)
              VALUES (3, '3', 'BALCAO LONDRES BRANCO C/FRUTA/ MARMORIZADO', 52.5, 52.5, 100);
INSERT INTO PRODUTOS (ID, CODIGO_BAR, DESCRICAO, PRECO_COMPRA, PRECO_VENDA, QTD_ESTOQUE)
              VALUES (4, '4', 'FRUTEIRA NOBRE BRANCO C/FRUTA / MARMORIZADO', 40, 40, 200);
INSERT INTO PRODUTOS (ID, CODIGO_BAR, DESCRICAO, PRECO_COMPRA, PRECO_VENDA, QTD_ESTOQUE)
              VALUES (5, '5', 'ACENTO KORINO PRETO', 6, 6, 300);
INSERT INTO PRODUTOS (ID, CODIGO_BAR, DESCRICAO, PRECO_COMPRA, PRECO_VENDA, QTD_ESTOQUE)
              VALUES (6, '6', 'BABY LIGHT D18 SELADO SM 0700X700X01400', 0, 0, 400);
INSERT INTO PRODUTOS (ID, CODIGO_BAR, DESCRICAO, PRECO_COMPRA, PRECO_VENDA, QTD_ESTOQUE)
              VALUES (7, '7', 'KIT ESPELHO ROUPEIRO PAMPULHA REF. 683 - ESPELHO', 46, 46, 500);
INSERT INTO PRODUTOS (ID, CODIGO_BAR, DESCRICAO, PRECO_COMPRA, PRECO_VENDA, QTD_ESTOQUE)
              VALUES (8, '8', 'KIT 6PTS PAMPULHA II REF. 683 PRETO/BRANCO/GEOMETRICO PTO', 186, 186, 100);
INSERT INTO PRODUTOS (ID, CODIGO_BAR, DESCRICAO, PRECO_COMPRA, PRECO_VENDA, QTD_ESTOQUE)
              VALUES (9, '9', 'KIT 6PTS PAMPULHA II REF. 683 PRETO/GRIGIO', 186, 186, 8);
INSERT INTO PRODUTOS (ID, CODIGO_BAR, DESCRICAO, PRECO_COMPRA, PRECO_VENDA, QTD_ESTOQUE)
              VALUES (1, '1', 'MONTAGEM  DE TESTE', 15, 15, 4);
INSERT INTO PRODUTOS (ID, CODIGO_BAR, DESCRICAO, PRECO_COMPRA, PRECO_VENDA, QTD_ESTOQUE)
              VALUES (10, '10', 'KIT 6PTS PAMPULHA II REF. 683 PRETO/CARVALHO', 186, 186, 5);
INSERT INTO PRODUTOS (ID, CODIGO_BAR, DESCRICAO, PRECO_COMPRA, PRECO_VENDA, QTD_ESTOQUE)
              VALUES (11, '11', 'KIT C/ 1 ESPELHO ROUP. COLORADO/FILADELFIA/MONT/PARD. IV -', 20, 20, 6);
INSERT INTO PRODUTOS (ID, CODIGO_BAR, DESCRICAO, PRECO_COMPRA, PRECO_VENDA, QTD_ESTOQUE)
              VALUES (12, '12', 'JG C/8 PES DE PLASTICO REF. 705 BRANCO', 14, 14, 100);
INSERT INTO PRODUTOS (ID, CODIGO_BAR, DESCRICAO, PRECO_COMPRA, PRECO_VENDA, QTD_ESTOQUE)
              VALUES (13, '13', 'JG C/8 PES DE PLASTICO REF. 705 CINZA', 13, 13, 1);
INSERT INTO PRODUTOS (ID, CODIGO_BAR, DESCRICAO, PRECO_COMPRA, PRECO_VENDA, QTD_ESTOQUE)
              VALUES (14, '14', 'JG C/8 PES DE PLASTICO REF. 705 TABACO', 8.84, 8.84, 5);
INSERT INTO PRODUTOS (ID, CODIGO_BAR, DESCRICAO, PRECO_COMPRA, PRECO_VENDA, QTD_ESTOQUE)
              VALUES (15, '15', 'DESPESAS COM FRETE', 1, 1, 69);
INSERT INTO PRODUTOS (ID, CODIGO_BAR, DESCRICAO, PRECO_COMPRA, PRECO_VENDA, QTD_ESTOQUE)
              VALUES (16, '16', 'EXPOSITOR DE COZINHA BRANCO (2444) BRANCO', 339, 339, 85);
INSERT INTO PRODUTOS (ID, CODIGO_BAR, DESCRICAO, PRECO_COMPRA, PRECO_VENDA, QTD_ESTOQUE)
              VALUES (17, '17', 'MESA ELEGANCE LAT MG BECHARA', 0, 0, 254);
INSERT INTO PRODUTOS (ID, CODIGO_BAR, DESCRICAO, PRECO_COMPRA, PRECO_VENDA, QTD_ESTOQUE)
              VALUES (18, '18', 'JG C/4 PES DE PLASTICO REF. 705 TABACO', 4.42, 4.42, 25);
INSERT INTO PRODUTOS (ID, CODIGO_BAR, DESCRICAO, PRECO_COMPRA, PRECO_VENDA, QTD_ESTOQUE)
              VALUES (19, '19', 'BANCADA TOPAZIO ATACAMA/PRETO', 398.04, 398.04, 48);
INSERT INTO PRODUTOS (ID, CODIGO_BAR, DESCRICAO, PRECO_COMPRA, PRECO_VENDA, QTD_ESTOQUE)
              VALUES (20, '20', 'MESA FOLHA C.MF BECHARA', 25, 25, 236);
INSERT INTO PRODUTOS (ID, CODIGO_BAR, DESCRICAO, PRECO_COMPRA, PRECO_VENDA, QTD_ESTOQUE)
              VALUES (21, '21', 'PAINEL AMETISTA ATACAMA/PRETO', 181.9, 181.9, 25);
INSERT INTO PRODUTOS (ID, CODIGO_BAR, DESCRICAO, PRECO_COMPRA, PRECO_VENDA, QTD_ESTOQUE)
              VALUES (22, '22', 'MESA ELEG CENTRO MF BECHARA', 84, 84, 563);
INSERT INTO PRODUTOS (ID, CODIGO_BAR, DESCRICAO, PRECO_COMPRA, PRECO_VENDA, QTD_ESTOQUE)
              VALUES (23, '23', 'DESPESAS COM MANUTENÇÃO', 100, 100, 21);
INSERT INTO PRODUTOS (ID, CODIGO_BAR, DESCRICAO, PRECO_COMPRA, PRECO_VENDA, QTD_ESTOQUE)
              VALUES (24, '24', 'MESA ELEGANCE LAT MF BECHARA', 0, 0, 25);
INSERT INTO PRODUTOS (ID, CODIGO_BAR, DESCRICAO, PRECO_COMPRA, PRECO_VENDA, QTD_ESTOQUE)
              VALUES (25, '25', 'ESTANTE ICARO MG BECHARA', 0, 0, 58);
INSERT INTO PRODUTOS (ID, CODIGO_BAR, DESCRICAO, PRECO_COMPRA, PRECO_VENDA, QTD_ESTOQUE)
              VALUES (26, '26', 'ESTANTE ICARO MF BECHARA', 0, 0, 2);
INSERT INTO PRODUTOS (ID, CODIGO_BAR, DESCRICAO, PRECO_COMPRA, PRECO_VENDA, QTD_ESTOQUE)
              VALUES (27, '27', 'FRUTEIRA TUBULAR', 60, 60, 3);
INSERT INTO PRODUTOS (ID, CODIGO_BAR, DESCRICAO, PRECO_COMPRA, PRECO_VENDA, QTD_ESTOQUE)
              VALUES (28, '28', 'CONJ C/4LUG TURB QUAD/RED', 75, 75, 3);
INSERT INTO PRODUTOS (ID, CODIGO_BAR, DESCRICAO, PRECO_COMPRA, PRECO_VENDA, QTD_ESTOQUE)
              VALUES (29, '29', 'MESA DIAMANTE P/ CHOCOLATE 1.55', 88.4, 88.4, 6);
INSERT INTO PRODUTOS (ID, CODIGO_BAR, DESCRICAO, PRECO_COMPRA, PRECO_VENDA, QTD_ESTOQUE)
              VALUES (30, '30', 'CADEIRA DIAMANTE P/CHOCOLATE/ASS.ENC.CHIN BR/MES', 32, 32, 5);
INSERT INTO PRODUTOS (ID, CODIGO_BAR, DESCRICAO, PRECO_COMPRA, PRECO_VENDA, QTD_ESTOQUE)
              VALUES (31, '31', 'PORTA TAUA STATUS ESP 4515 BCO/PRE', 83.12, 83.12, 8);
INSERT INTO PRODUTOS (ID, CODIGO_BAR, DESCRICAO, PRECO_COMPRA, PRECO_VENDA, QTD_ESTOQUE)
              VALUES (32, '1000233542200', 'REPIMBOCA DA PARAFUZETA O PAR', 10.25, 25.3, 1000);
INSERT INTO PRODUTOS (ID, CODIGO_BAR, DESCRICAO, PRECO_COMPRA, PRECO_VENDA, QTD_ESTOQUE)
              VALUES (33, '1000250002511', 'REPIMBOCA SEM A PARAFUZETA', 9.52, 22.5, 1000);
INSERT INTO PRODUTOS (ID, CODIGO_BAR, DESCRICAO, PRECO_COMPRA, PRECO_VENDA, QTD_ESTOQUE)
              VALUES (34, '1000255874000', 'PAR DE PARAFUZETA SEM SEMETRICA', 8.2, 10.5, 1000);

COMMIT WORK;
