/******************************************************************************/
/***               Generated by IBExpert 14/06/2024 16:28:51                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE PEDIDO_PRODUTOS (
    ID_PEDIDO       INTEGER NOT NULL,
    ID_PRODUTO      INTEGER NOT NULL,
    NUMPEDIDO       VARCHAR(10),
    QUANTIDADE      FLOAT,
    VALOR_UNITARIO  FLOAT,
    VALOR_TOTAL     INTEGER
);




/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE PEDIDO_PRODUTOS ADD CONSTRAINT FK_PEDIDO_PRODUTOS_1 FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO (ID);
ALTER TABLE PEDIDO_PRODUTOS ADD CONSTRAINT FK_PEDIDO_PRODUTOS_2 FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS (ID);


/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/

